# Generated by Django 4.0.3 on 2022-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('otp', models.IntegerField(null=True)),
                ('recieved_time', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('otp_expire_time', models.DateTimeField()),
                ('email_is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
