# Generated by Django 4.0.3 on 2022-03-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyotpapp', '0002_alter_verificationdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdetails',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
