# Generated by Django 4.0.3 on 2022-03-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyotpapp', '0003_verificationdetails_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=4)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
