# Generated by Django 4.0.3 on 2022-03-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyotpapp', '0005_otp_created_at_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
