# Generated by Django 4.0.3 on 2022-03-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifyotpapp', '0007_alter_otp_created_at_alter_otp_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
